spring:
  application:
    name: WindtBack
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/security_back_winderton
    username: postgres
    password: postgres
  jpa:
    database:  postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
server:
  port: 8081
wndtback:
  app:
    secret: 3yYVzp5nVElAYg123uRpOMq+fzQfFQ6OgoxTKuUz9Fg=
    lifetime: 60000
